name: native_video_utils
description: "A Flutter plugin designed to combat the issue of FFmpeg-Kit being abandoned and instead use native platform interfaces to edit videos."
version: 0.0.1
repository: https://github.com/konstanius/native_video_utils
issue_tracker: https://github.com/konstanius/native_video_utils/issues

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.konstanius.native_video_utils
        pluginClass: NativeVideoUtilsPlugin
      ios:
        pluginClass: NativeVideoUtilsPlugin
